# Generated by Django 4.2.28 on 2026-02-13 08:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Karfa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_initial', models.DecimalField(decimal_places=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant initial (GNF)')),
                ('montant_actuel', models.DecimalField(decimal_places=0, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant actuel (GNF)')),
                ('devise', models.CharField(default='GNF', editable=False, max_length=3, verbose_name='Devise')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_rendu_total', models.DateTimeField(blank=True, null=True, verbose_name='Date de restitution totale')),
                ('statut', models.CharField(choices=[('ACTIF', 'En main'), ('PARTIELLEMENT_RENDU', 'Partiellement rendu'), ('RENDU_TOTAL', 'Rendu totalement'), ('EN_LITIGE', 'En litige')], default='ACTIF', max_length=20, verbose_name='Statut')),
                ('motif', models.TextField(blank=True, verbose_name='Motif du dépôt')),
                ('justificatif', models.ImageField(blank=True, null=True, upload_to='karfa/justificatifs/%Y/%m/', verbose_name='Justificatif (photo/reçu)')),
                ('archive', models.BooleanField(default=False, verbose_name='Archivé')),
                ('date_archivage', models.DateTimeField(blank=True, null=True, verbose_name="Date d'archivage")),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karfas_recus', to=settings.AUTH_USER_MODEL, verbose_name='Bénéficiaire')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='karfas_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Karfa',
                'verbose_name_plural': 'Karfas',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='MouvementKarfa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CREATION', 'Création'), ('AJOUT', 'Ajout de fonds'), ('RETRAIT', 'Retrait/Restitution'), ('ANNULATION', 'Annulation')], max_length=20, verbose_name='Type de mouvement')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Montant (GNF)')),
                ('solde_apres', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Solde après opération (GNF)')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date du mouvement')),
                ('note', models.TextField(blank=True, verbose_name='Note/Commentaire')),
                ('justificatif', models.ImageField(blank=True, null=True, upload_to='karfa/mouvements/%Y/%m/', verbose_name='Justificatif')),
                ('effectue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_karfa', to=settings.AUTH_USER_MODEL, verbose_name='Effectué par')),
                ('karfa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='karfa.karfa', verbose_name='Karfa')),
            ],
            options={
                'verbose_name': 'Mouvement de Karfa',
                'verbose_name_plural': 'Mouvements de Karfa',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['karfa', '-date'], name='karfa_mouve_karfa_i_a74139_idx'), models.Index(fields=['type', 'date'], name='karfa_mouve_type_f4e33b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='karfa',
            constraint=models.UniqueConstraint(condition=models.Q(('archive', False)), fields=('beneficiaire', 'motif', 'date_creation'), name='unique_karfa_par_beneficiaire_motif_date'),
        ),
    ]
