# Generated by Django 6.0.2 on 2026-03-06 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karfa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouvementkarfa',
            name='effectue_par',
        ),
        migrations.AddField(
            model_name='mouvementkarfa',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_karfa', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
    ]
