# Generated by Django 6.0.2 on 2026-03-21 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karfa', '0002_remove_mouvementkarfa_effectue_par_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='karfa',
            name='beneficiaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karfas_recus', to=settings.AUTH_USER_MODEL, verbose_name='Bénéficiaire'),
        ),
    ]
