# Generated by Django 4.2.28 on 2026-02-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompteArgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Nom du compte')),
                ('sous_type', models.CharField(choices=[('BANQUE', 'Banque'), ('MOBILE_MONEY', 'Mobile Money'), ('CASH', 'Espèces'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Type de compte')),
                ('solde', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Solde (GNF)')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Compte actif')),
            ],
            options={
                'verbose_name': 'Compte Argent',
                'verbose_name_plural': 'Comptes Argent',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CompteOr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Nom du compte or')),
                ('poids_grammes', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Poids (grammes)')),
                ('carat', models.IntegerField(blank=True, null=True, verbose_name='Carat (optionnel)')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Compte actif')),
            ],
            options={
                'verbose_name': 'Compte Or',
                'verbose_name_plural': 'Comptes Or',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='PrixOr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_gramme', models.DecimalField(decimal_places=0, max_digits=12, verbose_name="Prix du gramme d'or (GNF)")),
                ('date_saisie', models.DateField(auto_now_add=True, verbose_name='Date de saisie')),
            ],
            options={
                'verbose_name': "Prix de l'or",
                'verbose_name_plural': "Prix de l'or",
                'ordering': ['-date_saisie'],
                'get_latest_by': 'date_saisie',
            },
        ),
    ]
