# Generated by Django 6.0.2 on 2026-02-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compteargent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='compteor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='prixor',
            options={},
        ),
        migrations.RemoveField(
            model_name='compteargent',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='compteargent',
            name='est_actif',
        ),
        migrations.RemoveField(
            model_name='compteargent',
            name='sous_type',
        ),
        migrations.RemoveField(
            model_name='compteor',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='compteor',
            name='est_actif',
        ),
        migrations.AddField(
            model_name='compteargent',
            name='type_compte',
            field=models.CharField(choices=[('BANQUE', 'Banque'), ('MOBILE_MONEY', 'Mobile Money'), ('CASH', 'Espèces'), ('AUTRE', 'Autre')], default='CASH', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compteargent',
            name='nom',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='compteargent',
            name='solde',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='compteor',
            name='carat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compteor',
            name='nom',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='compteor',
            name='poids_grammes',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='prixor',
            name='date_saisie',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prixor',
            name='prix_gramme',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
