# Generated by Django 4.2.28 on 2026-02-22 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_alter_compteargent_options_alter_compteor_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrixOr',
        ),
    ]
