# Generated by Django 4.2.28 on 2026-02-28 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comptes', '0003_delete_prixor'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteargent',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compteargent',
            name='date_archivage',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compteor',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compteor',
            name='date_archivage',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MouvementCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AJOUT', 'Ajout'), ('RETRAIT', 'Retrait')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=3, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('compte_argent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='comptes.compteargent')),
                ('compte_or', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='comptes.compteor')),
                ('effectue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
