# Generated by Django 6.0.2 on 2026-03-06 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_compteargent_archive_compteargent_date_archivage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compteargent',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comptes_argent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compteor',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comptes_or', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='compteargent',
            name='nom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='compteor',
            name='nom',
            field=models.CharField(max_length=50),
        ),
    ]
