# Generated by Django 6.0.2 on 2026-03-06 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0005_compteargent_cree_par_compteor_cree_par_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mouvementcompte',
            old_name='effectue_par',
            new_name='cree_par',
        ),
    ]
