# Generated by Django 4.2.28 on 2026-03-10 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dettes', '0005_dette_compte_debit'),
        ('comptes', '0006_rename_effectue_par_mouvementcompte_cree_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteargent',
            name='dette_liee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comptes_argent_lies', to='dettes.dette'),
        ),
        migrations.AlterField(
            model_name='compteargent',
            name='type_compte',
            field=models.CharField(choices=[('BANQUE', 'Banque'), ('MOBILE_MONEY', 'Mobile Money'), ('CASH', 'Espèces'), ('DETTE', 'Dettes'), ('AUTRE', 'Autre')], max_length=20),
        ),
    ]
