# Generated by Django 4.2.28 on 2026-02-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_application', models.CharField(default="N'Ka Wari", editable=False, max_length=50)),
                ('version', models.CharField(default='1.0.0', max_length=20, verbose_name='Version')),
                ('developpeur', models.CharField(default='Demba DOUMBOUYA', editable=False, max_length=100)),
                ('email', models.EmailField(default='Rodrigodoumbouya@gmail.com', editable=False, max_length=254)),
                ('telephone', models.CharField(default='+224 628 74 19 60', editable=False, max_length=20)),
                ('localisation', models.CharField(default='U-de Labé, Guinée', editable=False, max_length=100)),
                ('remerciements', models.TextField(default='Cheick Mohamed DIALLO', editable=False)),
            ],
            options={
                'verbose_name': 'À Propos',
                'verbose_name_plural': 'À Propos',
            },
        ),
        migrations.CreateModel(
            name='FormatParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_24h', models.BooleanField(default=True, verbose_name='Format 24h (sinon 12h AM/PM)')),
                ('format_date', models.CharField(default='DD/MM/YYYY', editable=False, max_length=20, verbose_name='Format de date')),
                ('langue', models.CharField(default='fr', editable=False, max_length=10, verbose_name='Langue')),
            ],
            options={
                'verbose_name': 'Paramètre - Format',
                'verbose_name_plural': 'Paramètres - Format',
            },
        ),
        migrations.CreateModel(
            name='PrixOrParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_gramme', models.DecimalField(decimal_places=0, max_digits=12, verbose_name="Prix du gramme d'or (GNF)")),
                ('date_saisie', models.DateTimeField(auto_now_add=True, verbose_name='Date de saisie')),
            ],
            options={
                'verbose_name': "Paramètre - Prix de l'or",
                'verbose_name_plural': "Paramètres - Prix de l'or",
                'get_latest_by': 'date_saisie',
            },
        ),
    ]
