# Generated by Django 6.0.2 on 2026-02-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_app', models.CharField(default="N'Ka Wari", max_length=50)),
                ('developpeur', models.CharField(default='Demba DOUMBOUYA', max_length=100)),
                ('email', models.EmailField(default='Rodrigodoumbouya@gmail.com', max_length=254)),
                ('telephone', models.CharField(default='+224 628 74 19 60', max_length=20)),
                ('localisation', models.CharField(default='U-de Labé, Guinée', max_length=100)),
                ('remerciements', models.TextField(default='Cheick Mohamed DIALLO')),
            ],
        ),
        migrations.CreateModel(
            name='Parametres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langue', models.CharField(default='fr', max_length=10)),
                ('format_date', models.CharField(default='DD/MM/YYYY', max_length=20)),
                ('format_heure', models.CharField(default='24h', max_length=10)),
                ('notifications', models.BooleanField(default=True)),
                ('version', models.CharField(default='1.0.0', max_length=10)),
            ],
            options={
                'verbose_name': 'Paramètre',
                'verbose_name_plural': 'Paramètres',
            },
        ),
        migrations.DeleteModel(
            name='AboutInfo',
        ),
        migrations.DeleteModel(
            name='FormatParam',
        ),
        migrations.DeleteModel(
            name='PrixOrParam',
        ),
    ]
