# Generated by Django 6.0.2 on 2026-03-06 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0003_migrate_prixor_from_comptes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prixorparam',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prix_or_params', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
    ]
