# Generated by Django 6.0.2 on 2026-03-17 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0004_prixorparam_cree_par'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametres',
            old_name='notifications',
            new_name='notifications_activees',
        ),
        migrations.AddField(
            model_name='parametres',
            name='theme',
            field=models.CharField(choices=[('clair', 'Clair'), ('sombre', 'Sombre')], default='clair', max_length=10),
        ),
        migrations.AddField(
            model_name='parametres',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parametres', to=settings.AUTH_USER_MODEL),
        ),
    ]
