# Generated by Django 6.0.2 on 2026-02-17 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sens', models.CharField(choices=[('JE_DOIS', 'Je dois'), ('ON_ME_DOIT', 'On me doit')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('montant_restant', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('personne', models.CharField(max_length=100)),
                ('motif', models.TextField(blank=True)),
                ('echeance', models.DateField(blank=True, null=True)),
                ('garantie', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('NON_PAYEE', 'Non payée'), ('PARTIELLEMENT_PAYEE', 'Partiellement payée'), ('PAYEE', 'Payée'), ('EN_LITIGE', 'En litige')], default='NON_PAYEE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_dernier_paiement', models.DateTimeField(blank=True, null=True)),
                ('archive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('dette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='dettes.dette')),
            ],
        ),
    ]
