# Generated by Django 4.2.28 on 2026-02-12 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('sens', models.CharField(choices=[('JE_DOIS', 'Je dois'), ('ON_ME_DOIT', 'On me doit')], max_length=20, verbose_name='Sens')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant (GNF)')),
                ('montant_restant', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant restant (GNF)')),
                ('personne', models.CharField(max_length=100, verbose_name='Créancier/Débiteur')),
                ('motif', models.TextField(blank=True, verbose_name='Motif')),
                ('echeance', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('garantie', models.TextField(blank=True, verbose_name='Garantie')),
                ('statut', models.CharField(choices=[('NON_PAYEE', 'Non payée'), ('PARTIELLEMENT_PAYEE', 'Partiellement payée'), ('PAYEE', 'Payée'), ('EN_LITIGE', 'En litige')], default='NON_PAYEE', max_length=25, verbose_name='Statut')),
                ('date_dernier_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Dernier paiement')),
            ],
            options={
                'verbose_name': 'Dette',
                'verbose_name_plural': 'Dettes',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant remboursé (GNF)')),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('dette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='dettes.dette')),
            ],
            options={
                'verbose_name': 'Remboursement',
                'verbose_name_plural': 'Remboursements',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
