# Generated by Django 6.0.2 on 2026-02-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dettes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remboursement',
            name='type',
            field=models.CharField(choices=[('AJOUT', 'Ajout'), ('REMBOURSEMENT', 'Remboursement'), ('ENCAISSEMENT', 'Encaissement')], default='REMBOURSEMENT', max_length=20),
        ),
    ]
