# Generated by Django 6.0.2 on 2026-02-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dettes', '0002_remboursement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dette',
            name='date_archivage',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
