# Generated by Django 4.2.28 on 2026-03-10 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0006_rename_effectue_par_mouvementcompte_cree_par'),
        ('dettes', '0004_dette_cree_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='dette',
            name='compte_debit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dettes_liees', to='comptes.compteargent'),
        ),
    ]
