# Generated by Django 6.0.2 on 2026-03-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dettes', '0005_dette_compte_debit'),
    ]

    operations = [
        migrations.AddField(
            model_name='dette',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
