# Generated by Django 4.2.28 on 2026-02-12 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karfa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karfa',
            name='montant_initial',
            field=models.DecimalField(decimal_places=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant initial (GNF)'),
        ),
        migrations.AlterField(
            model_name='mouvementkarfa',
            name='montant',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Montant (GNF)'),
        ),
        migrations.AlterField(
            model_name='mouvementkarfa',
            name='solde_apres',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Solde après opération (GNF)'),
        ),
    ]
